name: grn
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.12.8
  - pandas=2.2.3
  - numpy=1.26.4
  - scanpy=1.11.0
  - autopep8=2.3.2
  - isort=5.13.2
  - pylint=3.3.3
  - pytest=8.3.4
  - pytest-cov=6.0.0
  - pip=25.0.1
  - plotly=6.0.1
  - pip:
      - rpy2==3.5.17
